<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE hero_list [
    <!ELEMENT hero_name (miya, balmond, kagura, karina, tigreal, harley, kadita, wanwan, faramis, fanny)>
    <!ELEMENT hero_role (mm, fg, mg, ass, ts, ma, sm)>
    <!ELEMENT hero_specs (rd, dr, pr, rm, cc, bp, bc, br, gc, cr)>

    <!ELEMENT miya (#PCDATA)>
    <!ELEMENT balmond (#PCDATA)>
    <!ELEMENT kagura (#PCDATA)>
    <!ELEMENT karina (#PCDATA)>
    <!ELEMENT tigreal (#PCDATA)>
    <!ELEMENT harley (#PCDATA)>
    <!ELEMENT kadita (#PCDATA)>
    <!ELEMENT wanwan (#PCDATA)>
    <!ELEMENT faramis (#PCDATA)>
    <!ELEMENT fanny (#PCDATA)>

    <!ELEMENT mm (#PCDATA)>
    <!ELEMENT fg (#PCDATA)>
    <!ELEMENT mg (#PCDATA)>
    <!ELEMENT ass (#PCDATA)>
    <!ELEMENT ts (#PCDATA)>
    <!ELEMENT ma (#PCDATA)>
    <!ELEMENT sm (#PCDATA)>

    <!ELEMENT rd (#PCDATA)>
    <!ELEMENT dr (#PCDATA)>
    <!ELEMENT pr (#PCDATA)>
    <!ELEMENT rm (#PCDATA)>
    <!ELEMENT cc (#PCDATA)>
    <!ELEMENT bp (#PCDATA)>
    <!ELEMENT bc (#PCDATA)>
    <!ELEMENT br (#PCDATA)>
    <!ELEMENT gc (#PCDATA)>
    <!ELEMENT cr (#PCDATA)>
]>
<hero_list>
	<hero_name>
        <miya>Miya</miya>
        <balmond>Balmond</balmond>
        <kagura>Kagura</kagura>
        <karina>Karina</karina>
        <tigreal>Tigreal</tigreal>
        <harley>Harley</harley>
        <kadita>Kaditae</kadita>
        <wanwan>Wanwan</wanwan>
        <faramis>Faramis</faramis>
        <fanny>Fanny</fanny>
    </hero_name>
    <hero_role>
        <mm>Marksman</mm>
        <fg>Fighter</fg>
        <mg>Mage</mg>
        <ass>Assassin</ass>
        <ts>Tank|Support</ts>
        <ma>Mage|Assassin</ma>
        <sm>Support|Mage</sm>
    </hero_role>
    <hero_specs>
        <rd>Reap|Damage</rd>
        <dr>Damage|Regen</dr>
        <pr>Poke|Reap</pr>
        <rm>Reap|Magic Damage</rm>
        <cc>Crowd Control</cc>
        <bp>Burst|Poke</bp>
        <bc>Burst|Charge</bc>
        <br>Burst|Reap</br>
        <gc>Guard|Charge</gc>
        <cr>Chase|Reap</cr>
    </hero_specs>
</hero_list>
